# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Replace Macros
        run: |
          grep -rl "__PUBLISHER__" settings.xml | xargs sed -i s@"__PUBLISHER__"@"$PUBLISHER"@g
          grep -rl "__TOKEN__" settings.xml | xargs sed -i s@"__TOKEN__"@"$TOKEN"@g
        env:
          PUBLISHER: ${{ github.actor }}
          TOKEN: ${{ github.token }}

      - name: Compile with Maven
        run: mvn -B clean compile --file pom.xml -s settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml -s settings.xml

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: mvn deploy -s settings.xml